#!/bin/bash

echo "🔍 Vérification des clés requises dans locales/en.default.json"
echo "=============================================================="

file="locales/en.default.json"
missing_keys=()

# Fonction pour vérifier une clé
check_key() {
    local key="$1"
    
    if jq -e ".$key" "$file" > /dev/null 2>&1; then
        echo "✅ $key"
    else
        echo "❌ $key - MANQUANT"
        missing_keys+=("$key")
    fi
}

echo ""
echo "Vérification des clés general.*:"
check_key "general.accessibility.close"
check_key "general.policy.title" 
check_key "general.policy.default_content"
check_key "general.policy.last_updated"
check_key "general.menu"
check_key "general.all_rights_reserved"
check_key "general.secure_payments"
check_key "general.newsletter.name_placeholder"
check_key "general.newsletter.input_label"
check_key "general.newsletter.submit_button"
check_key "general.newsletter.confirmation_text"
check_key "general.breadcrumbs.home"
check_key "general.breadcrumbs.label"
check_key "general.cookies.consent"
check_key "general.quiz.question_of_html"
check_key "general.offcanvas_menu.title_customer"
check_key "general.pagination_page_of"

echo ""
echo "Vérification des clés collection.*:"
check_key "collection.filters.from"
check_key "collection.filters.title"
check_key "collection.filters.to"
check_key "collection.filters.view_more"
check_key "collection.filters.clear_all"
check_key "collection.filters.view_results"

echo ""
echo "Vérification des clés product.*:"
check_key "product.price_unit"
check_key "product.sold_out"
check_key "product.price_sale"
check_key "product.price_regular"
check_key "product.price_from"
check_key "product.color_options"
check_key "product.color_swatches"
check_key "product.in_stock"
check_key "product.out_of_stock"
check_key "product.product"
check_key "product.product_added_to_cart"
check_key "product.remove"
check_key "product.add"
check_key "product.add_to_cart"
check_key "product.buy_it_now"
check_key "product.include_taxes"
check_key "product.product_options"
check_key "product.quantity"
check_key "product.save"
check_key "product.select_variant"

echo ""
echo "Vérification des clés customer.*:"
check_key "customer.login.password"
check_key "customer.login.forgot_password"
check_key "customer.login.submit"
check_key "customer.login.new"
check_key "customer.login.create_account"
check_key "customer.login.email"
check_key "customer.recover_password.title"
check_key "customer.recover_password.success"
check_key "customer.recover_password.subtext"
check_key "customer.recover_password.submit"
check_key "customer.register.title"
check_key "customer.register.first_name"
check_key "customer.register.last_name"
check_key "customer.register.email"
check_key "customer.register.password"
check_key "customer.register.submit"
check_key "customer.register.have_account"
check_key "customer.register.login"
check_key "customer.reset_password.title"
check_key "customer.reset_password.subtext"
check_key "customer.reset_password.password"
check_key "customer.reset_password.password_confirm"
check_key "customer.reset_password.submit"
check_key "customer.account.title"
check_key "customer.account.logout"
check_key "customer.account.order_history"
check_key "customer.account.account_details"
check_key "customer.account.view_addresses"
check_key "customer.account.return"
check_key "customer.orders.none"
check_key "customer.orders.order_number"
check_key "customer.orders.date"
check_key "customer.orders.payment_status"
check_key "customer.orders.fulfillment_status"
check_key "customer.orders.total"
check_key "customer.activate_account.title"
check_key "customer.activate_account.subtext"
check_key "customer.activate_account.password"
check_key "customer.activate_account.password_confirm"
check_key "customer.activate_account.submit"
check_key "customer.activate_account.cancel"
check_key "customer.order.title"
check_key "customer.order.date_html"
check_key "customer.order.cancelled_html"
check_key "customer.order.cancelled_reason"
check_key "customer.order.product"
check_key "customer.order.sku"
check_key "customer.order.price"
check_key "customer.order.quantity"
check_key "customer.order.total"
check_key "customer.order.discount"
check_key "customer.order.shipping"
check_key "customer.order.tax"
check_key "customer.order.subtotal"
check_key "customer.order.billing_address"
check_key "customer.order.shipping_address"
check_key "customer.order.payment_status"
check_key "customer.order.fulfillment_status"
check_key "customer.order.track_shipment"
check_key "customer.order.fulfilled_at_html"

echo ""
echo "Vérification des clés custom.*:"
check_key "custom.title"
check_key "custom.description"
check_key "custom.ref_variant_label"

echo ""
echo "Vérification des clés footer.*:"
check_key "footer.newsletter.first_name_placeholder"
check_key "footer.newsletter.email_placeholder"
check_key "footer.newsletter.submit_button"

echo ""
echo "Vérification des clés sections.*:"
check_key "sections.location.section_heading"

echo ""
echo "=============================================================="
if [ ${#missing_keys[@]} -eq 0 ]; then
    echo "🎉 TOUTES LES CLÉS SONT PRÉSENTES !"
    exit 0
else
    echo "💥 ${#missing_keys[@]} clé(s) manquante(s) :"
    for key in "${missing_keys[@]}"; do
        echo "   - $key"
    done
    exit 1
fi
