#!/bin/bash

echo "🧪 TEST RAPIDE DU SYSTÈME COULEURS"
echo "=================================="

echo "✅ Vous avez déjà créé la couleur 'Red' manuellement"
echo "🎯 Testons directement le système avec cette couleur !"

echo ""
echo "📝 ÉTAPES POUR TESTER:"
echo "====================="
echo "1. 🌐 Allez dans: Online Store > Themes"
echo "2. ✏️  Cliquez 'Customize' sur votre thème actuel"
echo "3. 📄 Ouvrez une page produit (qui a des variantes)"
echo "4. 🔧 Ajoutez ce code temporairement dans le template:"
echo ""
echo "   Code à ajouter dans templates/product.liquid:"
echo "   =============================================="
echo '   {% render "color-system-test", product: product %}'
echo ""
echo "5. 💾 Sauvegardez et prévisualisez"
echo "6. 🔍 Vous devriez voir un test complet du système"

echo ""
echo "🎨 SI VOUS VOULEZ PLUS DE COULEURS:"
echo "==================================="
echo "Ajoutez manuellement ces couleurs dans Admin > Metaobjects > CSS Colors:"
echo ""
printf "%-15s %-10s %-10s\n" "Nom" "Hex" "CSS Code"
echo "----------------------------------------"
printf "%-15s %-10s %-10s\n" "Blue" "#0000FF" "blue"
printf "%-15s %-10s %-10s\n" "Green" "#008000" "green"
printf "%-15s %-10s %-10s\n" "Yellow" "#FFFF00" "yellow"
printf "%-15s %-10s %-10s\n" "Black" "#000000" "black"
printf "%-15s %-10s %-10s\n" "White" "#FFFFFF" "white"

echo ""
echo "🚀 COMMANDE POUR DÉPLOYER LE SNIPPET DE TEST:"
echo "=============================================="
echo "shopify theme push --only=snippets/color-system-test.liquid"

echo ""
echo "🎯 VOULEZ-VOUS:"
echo "==============="
echo "A) Tester maintenant avec juste 'Red' ?"
echo "B) Ajouter d'abord 4-5 couleurs manuellement ?"
echo "C) Essayer le script d'import corrigé ?"
echo ""
echo "Dites-moi: A, B, ou C ?"
